### ISSUE TITLE
We <3 Open Source

### ISSUE THREAD

**Issue by shane-kerr** [DNS-Resolver-BCP-TF/Resolver-Recommendations#7]
Someone needs to write some text about open source considerations

**Comment by maertsen** [comment]
Feel free to assign this to me. I don't have the privileges to do so myself. 

Do you mean for us to write in the `README.md`?

**Comment by shane-kerr** [comment]
I'm happy either with writing in the `README.md` directly or with a separate file.

**Comment by maertsen** [comment]
some first notes

  - open or closed licensing has no bearing security; neither is closed less secure on principle, nor are "unknown" contributions more of a risk in open.

pro:
  - open allows for inspection, independent auditing, and troubleshooting
  - open source can avoid vendor lock-in
  - the existence of widely deployed open source implementations aids standards development, because proponents of new developments can contribute proof of concept implementations without permission or cooperation of vendors

conn:
  - both open and closed require skilled maintenance, which has costs. Closed source software and appliances typically come with license fees to cover these. By contrast, open source by virtue of its license does not tie usage to monetary compensation. It is up to operators to think about diversity and continued sustainability of DNS implementations.

recommendation: 
  - ..
  - Financially support open-source DNS software to ensure continued development. Some maintainers take donations, other offer support contracts.

**Comment by shane-ns1** [comment]
There are both open source and proprietary implementations of DNS resolver software. Other modes are also possible, for example using proprietary extensions with open source software, or deploying software written in-house.

Neither openn or closed licensing has any bearing on security; neither is closed less secure on principle, nor are contributions by "unknown" developers  more of a risk in open source.

Benefits of open source

* open allows for inspection, independent auditing, and troubleshooting
* open source can avoid vendor lock-in
* the existence of widely-deployed open source implementations aids standards development, because proponents of new developments can contribute proof of concept implementations without permission or cooperation of vendors

Drawbacks of open source


It may be worthwhile deploying software you are already running, for example a company using Microsoft systems may wish to use their resolver.







recommendation:

    ..
    Financially support open-source DNS software to ensure continued development. Some maintainers take donations, other offer support contracts.

**Comment by moonshiner** [comment]
I have a note from a previous meeting for the Intro "Audience"

* Audience
  - Anonymous/Public
  - Account
  - Contract - Employees/Students

**Comment by maertsen** [comment]
PR #22 submitted; I believe we can close this issue if that work gets merged.

**Comment by moonshiner** [comment]
merged #22
